env: "lbf"  

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 20
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
epsilon_anneal_time: 250000


noise_epsilon: 0.03  #0.03   0.05
rnn_hidden_dim: 32
# --- VAE params ---
z_dim: 32
vae_hidden_dim: 64
robust_start_time: 800000

#
poe_loss_weight : 0.001  
vae_loss_weight : 0.01
robust_weight : 0.05
kappa : 5 # 5 10
weight_clamp : 0.3
