env: sc2

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "1o_10b_vs_1r" # 1o_10b_vs_1r , 1o_2r_vs_4r  
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False  # False, True
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False
  sight_range: 9
  
test_greedy: True
test_nepisode: 10
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000

noise_epsilon: 0.0075  #0.0075 0.015
rnn_hidden_dim: 64 
# --- VAE params ---
z_dim: 64 
vae_hidden_dim: 128 
robust_start_time: 1000000

#
poe_loss_weight : 0.01    
vae_loss_weight : 0.01   
robust_weight : 0.3 # 0.3 0.1
kappa : 10
weight_clamp : 0.3 # 0.3 0.2
